// ============================================================
// Email Infrastructure — mailto: URL builder + content templates
// ============================================================

import type {
  DailyLog,
  Project,
  NoticeLogEntry,
  LegalCorrespondence,
} from '@/lib/types';

// ── mailto: URL builder ──

interface MailtoParams {
  to?: string;
  subject: string;
  body: string;
  cc?: string;
}

export function buildMailtoUrl(params: MailtoParams): string {
  const to = params.to ? encodeURIComponent(params.to) : '';
  const parts: string[] = [];
  parts.push(`subject=${encodeURIComponent(params.subject)}`);
  parts.push(`body=${encodeURIComponent(params.body)}`);
  if (params.cc) parts.push(`cc=${encodeURIComponent(params.cc)}`);
  return `mailto:${to}?${parts.join('&')}`;
}

export function openMailto(params: MailtoParams): void {
  window.location.href = buildMailtoUrl(params);
}

// ── Email content generators ──

interface EmailContent {
  subject: string;
  body: string;
}

export function getDailyLogEmailContent(
  project: Project,
  log: DailyLog
): EmailContent {
  const formattedDate = fmtDate(log.date);
  const totalWorkers = log.manpower.reduce(
    (sum, m) => sum + m.journeymanCount + m.apprenticeCount + m.foremanCount,
    0
  );

  return {
    subject: `[FieldOps] Daily Log — ${project.name} — ${formattedDate}`,
    body: [
      `DAILY LOG — ${project.name}`,
      `Date: ${formattedDate}`,
      '',
      `Weather: ${log.weather.conditions}, ${log.weather.temperature}°F, Impact: ${log.weather.impact}`,
      `Workers on site: ${totalWorkers}`,
      `Equipment: ${log.equipment.length} pieces`,
      `Work items: ${log.workPerformed.length}`,
      `RFIs: ${log.rfis.length} | Submittals: ${log.submittals.length}`,
      `Inspections: ${log.inspections.length}`,
      `Changes: ${log.changes.length}`,
      `Conflicts: ${log.conflicts.length}`,
      log.notes ? `\nNotes:\n${log.notes}` : '',
      '',
      '---',
      'Please see attached PDF for full details.',
      'Generated by FieldOps — Blackstone Construction',
    ]
      .filter(Boolean)
      .join('\n'),
  };
}

export function getReportEmailContent(
  project: Project,
  formatType: string,
  weekLabel: string
): EmailContent {
  const formatLabels: Record<string, string> = {
    client: 'Client/Owner Report',
    design_team: 'Design Team Report',
    subcontractor: 'Subcontractor Report',
    internal: 'Internal Report',
  };

  return {
    subject: `[FieldOps] ${formatLabels[formatType] || 'Weekly Report'} — ${project.name} — ${weekLabel}`,
    body: [
      `${formatLabels[formatType] || 'Weekly Report'} — ${project.name}`,
      `Week: ${weekLabel}`,
      '',
      'Please see attached PDF for full report details.',
      '',
      'Generated by FieldOps — Blackstone Construction',
    ].join('\n'),
  };
}

export function getNoticeLogEmailContent(
  project: Project,
  notices: NoticeLogEntry[]
): EmailContent {
  const pending = notices.filter(
    (n) => n.responseRequired && !n.responseReceived
  ).length;
  const overdue = notices.filter((n) => {
    if (!n.responseRequired || n.responseReceived || !n.responseDeadline)
      return false;
    return new Date(n.responseDeadline) < new Date();
  }).length;

  return {
    subject: `[FieldOps] Notice Log — ${project.name}`,
    body: [
      `NOTICE LOG — ${project.name}`,
      '',
      `Total notices: ${notices.length}`,
      `Pending responses: ${pending}`,
      `Overdue: ${overdue}`,
      '',
      ...notices.slice(0, 10).map(
        (n) =>
          `- ${n.dateSent} | ${n.noticeType.replace(/_/g, ' ')} | To: ${n.sentTo} | ${n.responseReceived ? 'Response received' : 'Awaiting response'}`
      ),
      notices.length > 10 ? `... and ${notices.length - 10} more` : '',
      '',
      '---',
      'Please see attached PDF for full details.',
      'Generated by FieldOps — Blackstone Construction',
    ]
      .filter(Boolean)
      .join('\n'),
  };
}

export function getCausationEmailContent(
  project: Project,
  chainCount: number,
  totalCostImpact: number
): EmailContent {
  return {
    subject: `[FieldOps] Causation Analysis — ${project.name}`,
    body: [
      `CAUSATION ANALYSIS — ${project.name}`,
      '',
      `Total causation chains: ${chainCount}`,
      `Total cost impact: $${totalCostImpact.toLocaleString()}`,
      '',
      '---',
      'Please see attached PDF for full causation chain details.',
      'Generated by FieldOps — Blackstone Construction',
    ].join('\n'),
  };
}

export function getLegalLetterEmailContent(
  project: Project,
  letter: LegalCorrespondence,
  recipientEmail?: string
): { params: MailtoParams } {
  const typeLabels: Record<string, string> = {
    back_charge: 'Back Charge Notice',
    delay_notice: 'Delay Notice',
    cure_notice: 'Cure Notice',
    change_directive: 'Change Directive',
    rfi_followup: 'RFI Follow-Up',
    general: 'Correspondence',
  };

  const subject = `[FieldOps] ${typeLabels[letter.type] || 'Legal Correspondence'} — ${project.name}`;

  // Strip HTML tags from the generated letter for plain text body
  const plainBody = letter.generatedLetter
    ? stripHtml(letter.generatedLetter)
    : 'Please see attached PDF for the full letter.';

  // Truncate body to avoid mailto length limits
  const truncatedBody =
    plainBody.length > 1800
      ? plainBody.substring(0, 1800) + '\n\n[...truncated — see attached PDF for full text]'
      : plainBody;

  return {
    params: {
      to: recipientEmail || '',
      subject,
      body: [
        truncatedBody,
        '',
        '---',
        'Generated by FieldOps — Blackstone Construction',
      ].join('\n'),
    },
  };
}

function fmtDate(isoDate: string): string {
  return new Date(isoDate + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}

function stripHtml(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<li>/gi, '• ')
    .replace(/<\/h[1-6]>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}
